### ISSUE TITLE
Is it possible to choose whether or not to skew the non-foreground cards?

### ISSUE THREAD

**Issue by 0Franky** [delwar36/overlapped_carousel#2]
Hi @delwar36 
first of all, thank you for your contribution.

As the title suggest, I wanted to know if it is possible to choose whether or not to apply the rotation to cards that are not in the foreground (or choose how much to rotate them).

It would be a very convenient feature and I hope it will be possible to introduce it in the next version. 

Thanks in advance and have a nice day!

**Comment by Ultranmus** [comment]
Well you can do that. You can define the rotation. Just copy the code and inside the OverlappedCarouselCardItems class ,if you do not want rotation then in the matrix  getTransform remove the rotation line ..rotateY(-0.25 * distance) which i commented in the below code.

Matrix4 getTransform(int index) {
    final distance = centerIndex - index;

    var transform = Matrix4.identity()
      ..setEntry(3, 2, 0.007)
      // ..rotateY(-0.25 * distance)
      ..scale(1.25, 1.25, 1.25);
    if (index == centerIndex) transform.scale(1.05, 1.05, 1.05);
    return transform;
  }

**Comment by delwar36** [comment]
APOLOGY!!! Due to some busy schedules I am not being to update and rosolve the issues. I appreciate if anyone contributes to resolve the issues. Waiting for the PRs.

**Comment by yashas-hm** [comment]
Solved in PR #5
