### ISSUE TITLE
Is it possible to obscure (in a progressive way) the cards that are not in the foreground?

### ISSUE THREAD

**Issue by 0Franky** [delwar36/overlapped_carousel#3]
Hi @delwar36 
first of all, thank you for your contribution.

As the title suggest, I wanted to know if it is possible to obscure the cards (progressively) as they are far from the center.

It would be a very convenient feature and I hope it will be possible to introduce it in the next version. 

Thanks in advance and have a nice day!

**Comment by delwar36** [comment]
APOLOGY!!! Due to some busy schedules I am not being to update and resolve the issues. I appreciate if anyone contributes to resolve the issues. Waiting for the PRs.

**Comment by yashas-hm** [comment]
May I work towards this issue? @delwar36

**Comment by delwar36** [comment]
> May I work towards this issue? @delwar36

Sure, always welcome.

**Comment by yashas-hm** [comment]
@delwar36 Solved in PR #4
